// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4, duration: "30s", vus: 20 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "get_default_page",
    id: "5e4f0cf1-2727-4c07-96a0-b06eb5646531",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1/BlogStop/"
  });

  postman[Request]({
    name: "get_login_page",
    id: "71d58760-9ef7-445e-9f2e-4e77dc8c984e",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1/BlogStop/index.html"
  });

  postman[Request]({
    name: "login_user_fail_1",
    id: "c5edb53a-f1f8-4c72-9f21-6536c6458458",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/login",
    data:
      '{\n\t"username" : "tester",\n\t"password" : "09b4a15c-9e9b-11ea-a3cb-9cb6d0e0350e"\n}'
  });

  postman[Request]({
    name: "login_user_fail_2",
    id: "b0c79edb-71b9-4a38-bd12-1c6f97734cd9",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/login",
    data:
      '{\n\t"username" : "tester2",\n\t"password" : "09b4a15d-9e9b-11fa-a3cb-9cc6d0e0350e"\n}'
  });

  postman[Request]({
    name: "get_register_page",
    id: "e2b0a3be-8f0f-405b-8f1a-2555cb4f4570",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1/BlogStop/register.html"
  });

  postman[Request]({
    name: "register_user_1",
    id: "ad5050e0-a1c5-498b-8c44-07aa7e01de08",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/register",
    data:
      '{\n\t"username" : "tester",\n\t"password" : "09b4a15c-9e9b-11ea-a3cb-9cb6d0e0350e",\n\t"email" : "admin@gmail.com"\n}'
  });

  postman[Request]({
    name: "register_user_2",
    id: "be61417c-b22e-46c0-af6f-a1d0e20e7583",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/register",
    data:
      '{\n\t"username" : "tester2",\n\t"password" : "09b4a15d-9e9b-11fa-a3cb-9cc6d0e0350e",\n\t"email" : "tester2@gmail.com"\n}'
  });

  postman[Request]({
    name: "register_user_3",
    id: "ff9f733e-f888-49e4-9c59-363149d79db2",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/register",
    data:
      '{\n\t"username" : "tester3",\n\t"password" : "09b4a15e-6e9b-11fa-a3cb-abc6d0e0350e",\n\t"email" : "tester3@gmail.com"\n}'
  });

  postman[Request]({
    name: "register_user_4",
    id: "7d94910f-c3e5-40f8-a94f-4420885dac30",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/register",
    data:
      '{\n\t"username" : "tester4",\n\t"password" : "09b4b15e-6e9b-21fa-a7cb-abc6d0e1150e",\n\t"email" : "tester4@gmail.com"\n}'
  });

  postman[Request]({
    name: "login_user_1_success",
    id: "0115de72-6d61-4af0-bcff-94c6bfa4f8ae",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/login",
    data:
      '{\n\t"username" : "tester",\n\t"password" : "09b4a15c-9e9b-11ea-a3cb-9cb6d0e0350e"\n}'
  });

  postman[Request]({
    name: "login_user_2_success",
    id: "09693002-2966-4b6a-b9d6-d5bfe10dc54d",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/login",
    data:
      '{\n\t"username" : "tester2",\n\t"password" : "09b4a15d-9e9b-11fa-a3cb-9cc6d0e0350e"\n}'
  });

  postman[Request]({
    name: "login_user_3_success",
    id: "d441f53d-d7e5-4f40-9127-984815be7dc0",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/login",
    data:
      '{\n\t"username" : "tester3",\n\t"password" : "09b4a15e-6e9b-11fa-a3cb-abc6d0e0350e"\n}'
  });

  postman[Request]({
    name: "login_user_4_success",
    id: "3e1210aa-1646-4599-9efa-a21cac9d6368",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/login",
    data:
      '{\n\t"username" : "tester4",\n\t"password" : "09b4b15e-6e9b-21fa-a7cb-abc6d0e1150e"\n}'
  });

  postman[Request]({
    name: "check_user_1",
    id: "6221aa29-3dd4-4663-8ef3-1418eda6e053",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/check?username=tester"
  });

  postman[Request]({
    name: "check_user_2",
    id: "bb518f28-70f2-408a-827e-3c9f9eb3fdd8",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/check?username=tester2"
  });

  postman[Request]({
    name: "get_profile_user1",
    id: "de2da082-f871-4a0b-be29-aa091cac1650",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/profile?username=tester"
  });

  postman[Request]({
    name: "get_profile_user2",
    id: "eaa6044b-9292-4366-a006-0bdb39c7eb6b",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/profile?username=tester2"
  });

  postman[Request]({
    name: "get_profile_user3",
    id: "8c199798-842c-4696-a12c-e3c5e969ebde",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/profile?username=tester3"
  });

  postman[Request]({
    name: "get_profile_user4",
    id: "dd9c8185-e322-49cf-ab61-d47cdb023aa5",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/profile?username=tester4"
  });

  postman[Request]({
    name: "like_update_user1",
    id: "b24a4cc4-42f1-4cd4-9d10-7ce04bd8e68c",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/like_update?username=tester"
  });

  postman[Request]({
    name: "like_update_user2",
    id: "3f3ce19c-1810-4595-89a0-cc76edf5be60",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/like_update?username=tester2"
  });

  postman[Request]({
    name: "get_details_user1",
    id: "76f38f47-4c75-4897-ad62-036b4b72f4ef",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/get_details?username=tester"
  });

  postman[Request]({
    name: "get_details_user3",
    id: "0995cc78-6d21-4166-91e1-7a1e573c3b0e",
    method: "GET",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://127.0.0.1:5000/get_details?username=tester3"
  });
}
